# APT
apts:
  - gnome-shell-extension-manager
  - gnome-software-plugin-flatpak
  - gnome-weather
  - gnome-tweaks
  - neofetch
  - speedtest-cli
  - mc
  - adb
  - bat
  - geoip-bin
  - flatpak
  - tilix
  - zsh
  - nvtop
  - smartmontools
  - yt-dlp
  - sshpass
#  - terraform
  - wget
  - jq
  - sed
  - unzip
  - timeshift # conf
  - vim
  - tlp
  - tlp-rdw
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

debs:
  - http://repo.yandex.ru/yandex-disk/yandex-disk_latest_amd64.deb

bins_archive: # to /usr/sbin
  - url: https://www.hdsentinel.com/hdslin/hdsentinel-020b-x64.zip
    name: HDSentinel

flatpak_repo: "https://dl.flathub.org/repo/flathub.flatpakrepo"

flatpaks:
  - org.gnome.Evolution
  - org.telegram.desktop
  - com.google.Chrome
  - ru.yandex.Browser
  - org.filezillaproject.Filezilla
  - com.jetbrains.DataGrip
  - io.mpv.Mpv # conf
  - org.gimp.GIMP
  - org.onlyoffice.desktopeditors
  - org.keepassxc.KeePassXC
  - org.getoutline.OutlineManager
  - org.getoutline.OutlineClient
  - dev.k8slens.OpenLens
  - com.valvesoftware.Steam
  - org.qbittorrent.qBittorrent
  - com.slack.Slack
  - org.remmina.Remmina
  - net.cozic.joplin_desktop

services_enabled:
  - tlp.service

gnome_extensions:
  - id: 8
    name: places-status-indicator
  - id: 517
    name: caffeine
  - id: 4679
    name: burn-my-windows
  - id: 5985
    name: do-not-disturb-while-screen-sharing-or-recording
  - id: 5410
    name: grand-theft-focus
  - id: 4451
    name: logo-menu
  - id: 1460
    name: vitals
  - id: 5904
    name: volume-scroller
  - id: 5470
    name: weather-oclock
#  - id: 5278
#    name: pano # no 46 support # https://github.com/oae/gnome-shell-pano/issues/271
#  - id: 2594
#    name: always-indicator # no 46 support # https://github.com/mzur/gnome-shell-always-indicator/issues/21

gnome_extensions_zip: #name should be uuid from metadata.json
  - url: "https://github.com/harshadgavali/gnome-gesture-improvements/files/14779174/gestureImprovements46%40gestures.zip"
    name: gestureImprovements@gestures

gnome_extension_dir: "/home/{{ ansible_env.USER }}/.local/share/gnome-shell/extensions/"

zsh_custom_plugins:
  - url: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    name: zsh-syntax-highlighting

zsh_custom_plugins_dir: "/home/{{ ansible_env.USER }}/.oh-my-zsh/custom/plugins/"
